#!/usr/bin/env python3
"""
VGold Phase 1 — CRM import builder.

Reads the live CRM phpMyAdmin dump and produces ONE deterministic SQL file
(`migration/sql/crm_data_import.sql`) that, when applied to the unified VGold
database, imports every CRM table VERBATIM under a `crm_` prefix.

Approach (lossless, exact):
  * Take each real `CREATE TABLE `<t>` (...) ...;` block from the dump and:
      - rename the table to `crm_<t>`
      - DROP any `CONSTRAINT ... FOREIGN KEY ...` lines (cross-table FKs are
        re-created internally between crm_ tables by 011_crm_integration.sql,
        and we don't want FKs pointing at the VGo `users`/`leads` tables).
      - normalise `int(11)` -> `int` etc. is NOT needed (MySQL accepts both);
        we keep the DDL as-is for fidelity.
  * Take each `INSERT INTO `<t>` ...;` block and rewrite the target to
    `crm_<t>` verbatim (values untouched — full fidelity, all rows).
  * Wrap in FK-safe ordering: SET FOREIGN_KEY_CHECKS=0 during load.

The users reconciliation (crm_users -> unified users, by email) is handled
separately by `reconcile_users.py` after this data is loaded.
"""
import re, sys, io, os

DUMP = sys.argv[1] if len(sys.argv) > 1 else "/home/user/uploaded_files/dbg8w2f3gdgcjw.sql"
OUT  = sys.argv[2] if len(sys.argv) > 2 else "/home/user/vgold/migration/sql/crm_data_import.sql"

with io.open(DUMP, encoding="utf-8", errors="replace") as f:
    sql = f.read()

# CRM tables to import (all 21). Order chosen so that parent tables load first,
# though FK checks are disabled during load anyway.
TABLES = [
    "users", "leads", "interactions", "documents", "proposals",
    "activity_log", "voip_calls", "whatsapp_messages", "notifications",
    "automation_rules", "automation_logs",
    "email_campaigns", "email_campaign_log", "email_lists",
    "email_list_members", "email_templates", "whatsapp_templates",
    "knowledge_hub_cards", "settings", "webhook_endpoints", "webhook_log",
]

def extract_create(table):
    # Match: CREATE TABLE `table` ( ... ) ENGINE=...;
    pat = re.compile(
        r"CREATE TABLE `%s` \((.*?)\n\) ([^;]*);" % re.escape(table),
        re.S)
    m = pat.search(sql)
    if not m:
        return None
    body, tail = m.group(1), m.group(2)
    # Normalise collation/charset to the unified VGold default (utf8mb4_unicode_ci).
    # The CRM dump uses utf8mb4_0900_ai_ci which conflicts with VGo's unicode_ci
    # in JOIN/= comparisons. Strip the table-level CHARSET/COLLATE from the tail
    # and any inline COLLATE on individual columns.
    tail = re.sub(r"DEFAULT CHARSET=\w+", "DEFAULT CHARSET=utf8mb4", tail)
    tail = re.sub(r"COLLATE=\w+", "COLLATE=utf8mb4_unicode_ci", tail)
    if "COLLATE=" not in tail:
        tail = tail.rstrip() + " COLLATE=utf8mb4_unicode_ci"
    # Remove per-column COLLATE clauses so they inherit the table default.
    body = re.sub(r"\s+COLLATE\s+\w+", "", body)
    body = re.sub(r"\s+CHARACTER SET\s+\w+", "", body)
    # Drop FK constraint lines (and any leading comma/newline)
    lines = body.split("\n")
    kept = []
    for ln in lines:
        stripped = ln.strip().rstrip(",")
        if stripped.upper().startswith("CONSTRAINT ") and "FOREIGN KEY" in stripped.upper():
            continue
        kept.append(ln)
    # Re-join and fix a possible trailing comma before ')'
    new_body = "\n".join(kept)
    new_body = re.sub(r",\s*$", "", new_body.rstrip())
    ddl = "DROP TABLE IF EXISTS `crm_%s`;\nCREATE TABLE `crm_%s` (%s\n) %s;" % (
        table, table, new_body, tail)
    return ddl

def extract_inserts(table):
    # phpMyAdmin emits: INSERT INTO `table` (...) VALUES (...),(...);  possibly many
    out = []
    for m in re.finditer(r"INSERT INTO `%s` " % re.escape(table), sql):
        start = m.start()
        # find the terminating ";\n" for this statement (respect quoted ';')
        i = m.end()
        depth_str = False
        esc = False
        j = i
        while j < len(sql):
            ch = sql[j]
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == "'":
                depth_str = not depth_str
            elif ch == ";" and not depth_str:
                break
            j += 1
        stmt = sql[start:j+1]
        stmt = stmt.replace("INSERT INTO `%s` " % table,
                            "INSERT INTO `crm_%s` " % table, 1)
        out.append(stmt)
    return out

parts = []
parts.append("-- AUTO-GENERATED by migration/build_crm_import.py — do not edit by hand.")
parts.append("-- Imports live CRM data verbatim into crm_* tables in the unified DB.")
parts.append("SET FOREIGN_KEY_CHECKS=0;")
parts.append("SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';")

missing = []
for t in TABLES:
    ddl = extract_create(t)
    if ddl is None:
        missing.append(t)
        continue
    parts.append("\n-- ===== %s =====" % t)
    parts.append(ddl)
    for ins in extract_inserts(t):
        parts.append(ins)

parts.append("\nSET FOREIGN_KEY_CHECKS=1;")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with io.open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(parts) + "\n")

print("Wrote:", OUT)
print("Tables emitted:", len(TABLES) - len(missing))
if missing:
    print("MISSING (not found in dump):", missing)
